# Analysis Methods {#sec-methods}

```{r setup, file = "R/chapter_start.R", include = FALSE}
# a number of commands need to run at the beginning of each chapter. This
# includes loading libraries that I always use, as well as options for 
# displaying numbers and text.
```

```{r setup2, include = FALSE}
# Other packages ------
# These are packages that get used in this chapter but aren't part of the default set.
library(targets)
library(mlogit)

find_mode <- function(x) {
  u <- unique(x)
  tab <- tabulate(match(x, u))
  u[tab == max(tab)]
}
```



## Data

```{r loaddata}
demo <- tar_read(demographics_table) 

demo <- demo |> 
  group_by(userId) |> 
  summarize(
    group = find_mode(Prescribed_Group),
    response_pct = max(Total_response_percentage),
    age = find_mode(Age), 
    gender = find_mode(Gender), 
    sex = find_mode(Sex)
  )
```
Participants were prescribed a group based on a psychological evaluation as
being a social anxiet

@tbl-stats presents basic demographic statistics of the study participants
by prescribed group.
Approximately 70% of the participants are female in sex and gender, and the
average age in all three 

```{r stats}
#| label: tbl-stats
#| tbl-cap: Descriptive Statistics

datasummary_balance(~ group , 
                    data = demo |>  
                      transmute(
                        group,
                        `Response Percent` = response_pct,
                        `Age` = age,
                        `Gender` = gender,
                        `Sex` = sex
                      ), digits = 2)
```


## Spatial Processing Algorithm
