<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-99.9.9">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="keywords" content="travel behavior, mental health, motivation, suicidality, activity types, DBSCAN-TE">

<title>4&nbsp; Results and Discussions – Exploring the Link Between Travel Behavior and Mental Health</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05_conclusions.html" rel="next">
<link href="./03_methods.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_results.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Results and Discussions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Exploring the Link Between Travel Behavior and Mental Health</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_litreview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literature Review</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Methodology</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_results.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Results and Discussions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_conclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conclusions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_limitations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Limitations and Future Recommendations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acknowledgments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgments</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#activity-engagement-by-group" id="toc-activity-engagement-by-group" class="nav-link active" data-scroll-target="#activity-engagement-by-group"><span class="header-section-number">4.1</span> Activity Engagement by Group</a></li>
  <li><a href="#motivation-by-group" id="toc-motivation-by-group" class="nav-link" data-scroll-target="#motivation-by-group"><span class="header-section-number">4.2</span> Motivation by Group</a></li>
  <li><a href="#suicidal-ideation-by-group" id="toc-suicidal-ideation-by-group" class="nav-link" data-scroll-target="#suicidal-ideation-by-group"><span class="header-section-number">4.3</span> Suicidal Ideation by Group</a></li>
  <li><a href="#model-comparison-and-evaluation" id="toc-model-comparison-and-evaluation" class="nav-link" data-scroll-target="#model-comparison-and-evaluation"><span class="header-section-number">4.4</span> Model Comparison and Evaluation</a></li>
  <li><a href="#effect-of-demographic-factors-on-motivation" id="toc-effect-of-demographic-factors-on-motivation" class="nav-link" data-scroll-target="#effect-of-demographic-factors-on-motivation"><span class="header-section-number">4.5</span> Effect of Demographic Factors on Motivation</a></li>
  <li><a href="#models-by-group" id="toc-models-by-group" class="nav-link" data-scroll-target="#models-by-group"><span class="header-section-number">4.6</span> Models by Group</a>
  <ul class="collapse">
  <li><a href="#motivation-and-number-of-activities" id="toc-motivation-and-number-of-activities" class="nav-link" data-scroll-target="#motivation-and-number-of-activities"><span class="header-section-number">4.6.1</span> Motivation and Number of Activities</a></li>
  <li><a href="#motivation-and-suicidal-ideation" id="toc-motivation-and-suicidal-ideation" class="nav-link" data-scroll-target="#motivation-and-suicidal-ideation"><span class="header-section-number">4.6.2</span> Motivation and Suicidal Ideation</a></li>
  </ul></li>
  <li><a href="#activity-types" id="toc-activity-types" class="nav-link" data-scroll-target="#activity-types"><span class="header-section-number">4.7</span> Activity Types</a>
  <ul class="collapse">
  <li><a href="#activities-at-parks" id="toc-activities-at-parks" class="nav-link" data-scroll-target="#activities-at-parks"><span class="header-section-number">4.7.1</span> Activities at Parks</a></li>
  <li><a href="#activities-at-grocery-stores" id="toc-activities-at-grocery-stores" class="nav-link" data-scroll-target="#activities-at-grocery-stores"><span class="header-section-number">4.7.2</span> Activities at Grocery Stores</a></li>
  <li><a href="#activity-impact-on-motivation" id="toc-activity-impact-on-motivation" class="nav-link" data-scroll-target="#activity-impact-on-motivation"><span class="header-section-number">4.7.3</span> Activity Impact on Motivation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Results and Discussions</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>travel behavior, mental health, motivation, suicidality, activity types, DBSCAN-TE</p>
  </div>
</div>

</header>


<p>Analyzing travel behavior and mental well-being requires a comprehensive examination of the individual’s group. It is important to look at various factors related to how these groups travel and how their travel affects their well-being. Understanding the number and type of activities they engage in, motivational levels, and propensity towards suicidal ideation provides valuable insights for this analysis.</p>
<section id="activity-engagement-by-group" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="activity-engagement-by-group"><span class="header-section-number">4.1</span> Activity Engagement by Group</h2>
<p>This analysis examined the activity engagement patterns of the three groups: control, autism, and social anxiety. We analyzed the total number of activities and the seven-day rolling average number of activities for individuals in these groups. The descriptive statistics in <a href="#tbl-groupActs" class="quarto-xref">Table&nbsp;<span>4.1</span></a> describe these results for each group.</p>
<div class="cell">
<div id="tbl-groupActs" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-groupActs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.1: Activity Descriptive Statistics by Group
</figcaption>
<div aria-describedby="tbl-groupActs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Control (N=1706)
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Autism (N=804)
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Social Anxiety (N=1893)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Std. Dev.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Std. Dev.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Std. Dev.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No. of Activities</td>
<td style="text-align: center;">3.0</td>
<td style="text-align: center;">2.7</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">2.3</td>
<td style="text-align: center;">2.6</td>
<td style="text-align: center;">2.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sev-Day No. of Acts.</td>
<td style="text-align: center;">3.0</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">2.0</td>
<td style="text-align: center;">1.4</td>
<td style="text-align: center;">2.6</td>
<td style="text-align: center;">1.7</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Individuals in the control group engaged in an average of 3.0 activities, while the autism group averaged 2.1, and the social anxiety group averaged 2.6 activities. Standard deviations for the groups ranged from 2.3 to 2.7. A seven-day rolling average of activities showed similar trends but with slightly lower variability.</p>
<p>An ANOVA test revealed significant differences in the mean number of activities between the groups, with an F value of 32.97 and a p-value less than 0.001, indicating that the variation across groups was statistically significant. <a href="#fig-ANOVAActs" class="quarto-xref">Figure&nbsp;<span>4.1</span></a> displays the mean activities and 95% confidence intervals for group differences.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ANOVAActs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ANOVAActs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_results_files/figure-html/fig-ANOVAActs-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ANOVAActs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: Mean number of activities by group.
</figcaption>
</figure>
</div>
</div>
</div>
<p>After finding significant differences in activity levels among the three groups, a Tukey’s Honest Significant Difference (HSD) test identified specific group differences. Individuals in the autism group participated in significantly fewer activities than the control group, with a mean difference of -0.896 (p &lt; 0.001), and compared to the social anxiety group, with a mean difference of -0.375 (p &lt; 0.001). Similarly, the social anxiety group engaged in fewer activities than the control group, with a mean difference of -0.521 (p &lt; 0.001).</p>
<p>These results show significant differences in activity engagement across groups, with individuals with autism and social anxiety participating less than those in the control group. This underscores the importance of considering group differences when analyzing activity patterns and mental health outcomes.</p>
</section>
<section id="motivation-by-group" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="motivation-by-group"><span class="header-section-number">4.2</span> Motivation by Group</h2>
<p>We observed notable differences in well-being among the groups. Based on existing literature, we expected that individuals in the autism and social anxiety groups would report lower well-being compared to the control group. Using motivation as an indicator of well-being, we analyzed motivation levels from the evening survey, rated on a 1-100 scale. <a href="#tbl-groupMotiv" class="quarto-xref">Table&nbsp;<span>4.2</span></a> presents the mean and standard deviation of motivation for each group.</p>
<div class="cell">
<div id="tbl-groupMotiv" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-groupMotiv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.2: Motivation Levels by Group
</figcaption>
<div aria-describedby="tbl-groupMotiv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Control (N=1706)
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Autism (N=804)
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Social Anxiety (N=1893)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Std. Dev.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Std. Dev.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Std. Dev.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Motivation</td>
<td style="text-align: center;">47.7</td>
<td style="text-align: center;">14.2</td>
<td style="text-align: center;">34.0</td>
<td style="text-align: center;">19.4</td>
<td style="text-align: center;">40.3</td>
<td style="text-align: center;">18.5</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>The findings revealed differences in motivation across the groups. The control group had the highest mean motivation score of 47.7, with the lowest variability (standard deviation of 14.2), falling slightly below the middle range of the “typical motivation” category. The autism group had the lowest mean score of 34.0, with the highest variability (standard deviation of 19.4), falling in the “enough motivation to get by” category. The social anxiety group had a mean score of 40.3, falling between the other two groups and on the lowest end of the “typical motivation” category. An ANOVA test confirmed significant differences in motivation levels among the groups, with an F value of 362 and a p-value less than 0.001, indicating that these differences are statistically significant.</p>
<p>After confirming significant differences in motivation levels among the three groups, a Tukey’s HSD test was conducted to identify specific group differences. The autism group had a significantly lower mean motivation level than the control group, with a difference of -9.99 points. The social anxiety group also had a significantly lower motivation level compared to the control group, with a difference of -7.74 points. When comparing the autism and social anxiety groups, the social anxiety group had a significantly higher motivation level by 2.25 points. All differences had p-values less than 0.001.</p>
<p>These results highlight significant differences in motivation levels, with the control group showing higher motivation than both the autism and social anxiety groups, and the social anxiety group showing higher motivation than the autism group. This pattern underscores the impact that the group has on an individual’s motivation.</p>
</section>
<section id="suicidal-ideation-by-group" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="suicidal-ideation-by-group"><span class="header-section-number">4.3</span> Suicidal Ideation by Group</h2>
<p>The morning and evening surveys included different questions pertaining to suicidal ideation. The dataset presents an insightful glimpse into the prevalence of suicidal ideation within the groups, shedding light on potential differences in mental health concerns among them. We examined responses to the question “Have you thought about killing yourself in the past 12 hours or since you last took a survey?” across the three groups, where responses were “Yes,” “No,” or “No Response.” The responses to this question are summarized by group in <a href="#tbl-groupSuicide" class="quarto-xref">Table&nbsp;<span>4.3</span></a>.</p>
<div class="cell">
<div id="tbl-groupSuicide" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-groupSuicide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.3: Suicidal Ideation by Group
</figcaption>
<div aria-describedby="tbl-groupSuicide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Control (N=1706)
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Autism (N=804)
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Social Anxiety (N=1893)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Pct.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Pct.</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Pct.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Suicidal Ideation</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">2.1</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">4.9</td>
<td style="text-align: center;">296</td>
<td style="text-align: center;">15.6</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">No</td>
<td style="text-align: center;">1133</td>
<td style="text-align: center;">66.4</td>
<td style="text-align: center;">415</td>
<td style="text-align: center;">51.6</td>
<td style="text-align: center;">737</td>
<td style="text-align: center;">38.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">No Response</td>
<td style="text-align: center;">537</td>
<td style="text-align: center;">31.5</td>
<td style="text-align: center;">350</td>
<td style="text-align: center;">43.5</td>
<td style="text-align: center;">860</td>
<td style="text-align: center;">45.4</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>In the control group, participants reported no suicidal ideation on 66.4% of days and acknowledged suicidal thoughts on 2.1% of days. In the autism group, 51.6% of days were reported as ideation-free, while 4.9% of days involved suicidal ideation. The social anxiety group showed a different pattern, with no ideation reported on only 38.9% of days and ideation present on 15.6% of days. Some respondents across all groups chose not to answer, indicating the sensitive nature of the question.</p>
<p>A contingency table was constructed to organize the responses (“Yes,” “No,” or “No Response”) by group, and a chi-square test of independence was performed. The test yielded a chi-square statistic of 388.06 with 4 degrees of freedom, and a p-value less than 0.001, indicating a significant association between group and suicidal ideation responses. This suggests that grouptypology influences the likelihood of reporting suicidal ideation, highlighting differences in how individuals from each group experience suicidal thoughts.</p>
</section>
<section id="model-comparison-and-evaluation" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="model-comparison-and-evaluation"><span class="header-section-number">4.4</span> Model Comparison and Evaluation</h2>
<p>As discussed previously, we ran three different models to analyze the effect of the seven-day rolling average number of activities on motivation levels. We ran the OLS, FE, and RE models with robust standard errors and t-statistics due to the potential for autocorrelation and heteroskedasticity. The results of these three models are shown in <a href="#tbl-olsfere" class="quarto-xref">Table&nbsp;<span>4.4</span></a>.</p>
<div class="cell" data-warnings="false">
<div id="tbl-olsfere" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-warnings="false">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-olsfere-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.4: OLS, FE, and RE Models
</figcaption>
<div aria-describedby="tbl-olsfere-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">OLS</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">FE</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">RE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sev-Day No. of Acts.</td>
<td style="text-align: center;">1.420***</td>
<td style="text-align: center;">0.287+</td>
<td style="text-align: center;">0.362*</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(9.057)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(1.691)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(2.174)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No. of Obs.</td>
<td style="text-align: center;">4,211</td>
<td style="text-align: center;">4,211</td>
<td style="text-align: center;">4,211</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">35,969.8</td>
<td style="text-align: center;">34,519.76</td>
<td style="text-align: center;">34,596.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R²</td>
<td style="text-align: center;">0.021</td>
<td style="text-align: center;">0.001</td>
<td style="text-align: center;">0.047</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Robust t-statistics in parentheses. + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<p>We used the Hausman test to compare the RE and FE models. The test checks whether the RE model estimates are consistent and efficient compared to the FE estimates. The null hypothesis assumes RE estimates are consistent and efficient, while the alternative supports the FE model. With a p-value of 0.0013 (less than 0.05), we reject the null hypothesis, indicating that the RE model is inconsistent. Therefore, the FE model is more appropriate and was used for the remainder of the analysis.</p>
</section>
<section id="effect-of-demographic-factors-on-motivation" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="effect-of-demographic-factors-on-motivation"><span class="header-section-number">4.5</span> Effect of Demographic Factors on Motivation</h2>
<p>Given the Hausman test results, we used the FE model for analyzing activity patterns and mental health data. A limitation of the FE model is its inability to account for time-constant variables. To address this, we performed a linear regression to assess how demographic factors (e.g., sex, age, IQ score, and group) are associated with the intercepts from the FE model. This linear regression is described generally in <a href="#eq-linreg" class="quarto-xref">Equation&nbsp;<span>4.1</span></a></p>
<p><span id="eq-linreg"><span class="math display">\[
\bar{y}_{i} \; \tilde{} \; \beta (\vec{X}_{it})
\tag{4.1}\]</span></span></p>
<p>This allows us to understand how the baseline levels of motivation differ across groups. The sex, age, IQ score, and group were the independent variables, and the FE intercept values for each userID served as the dependent variable. The results from this model are shown in <a href="#tbl-fedemolm" class="quarto-xref">Table&nbsp;<span>4.5</span></a>.</p>
<div class="cell">
<div id="tbl-fedemolm" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-fedemolm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.5: Fixed Effects and Demographics Regression
</figcaption>
<div aria-describedby="tbl-fedemolm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">&amp;nbsp;Intercept Model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Female</td>
<td style="text-align: center;">−6.351 (−2.265)*</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: center;">0.089 (0.192)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IQ Score</td>
<td style="text-align: center;">−0.058 (−0.617)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Autism</td>
<td style="text-align: center;">−10.247 (−3.139)**</td>
</tr>
<tr class="odd">
<td style="text-align: left; box-shadow: 0px 1.5px;">Social Anxiety</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">−8.544 (−3.164)**</td>
</tr>
<tr class="even">
<td style="text-align: left;">No. of Obs.</td>
<td style="text-align: center;">62</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Log. Liklihood</td>
<td style="text-align: center;">−222.022</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">458.044</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R²</td>
<td style="text-align: center;">0.264</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> t-statistics in parentheses. + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<p>The analysis revealed significant findings regarding motivation levels. Being female was associated with a decrease of 6.351 points in motivation compared to males, with a statistically significant p-value less than 0.05. Age and IQ score did not show significant associations. In contrast, individuals with autism had a substantial decrease in motivation of 10.247 points compared to the control group, while those with social anxiety experienced an 8.544 point decrease, both with p-values less than 0.01. These results indicate that sex and group status significantly influence motivation levels, while age and IQ score have limited impact. The model explained approximately 26.4% of the variance in motivation, suggesting that other factors may also contribute. Overall, these findings highlight the importance of considering individual differences, particularly sex and group status, in examining motivation, with a focus on group typology for further exploration.</p>
</section>
<section id="models-by-group" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="models-by-group"><span class="header-section-number">4.6</span> Models by Group</h2>
<p>After identifying statistical differences in mean motivation, number of activities, and suicidal tendencies across the three groups, we opted to model each group separately. This approach aims to capture the unique characteristics and behaviors within each group, potentially revealing more nuanced relationships between variables and outcomes. Given the need for a FE model to account for individual differences, this method ensures that both observed and unobserved participant characteristics are considered in the analysis. Moving forward, we will employ FE models for each group, allowing us to explore factors influencing motivation while accounting for the distinct attributes of each subgroup.</p>
<section id="motivation-and-number-of-activities" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="motivation-and-number-of-activities"><span class="header-section-number">4.6.1</span> Motivation and Number of Activities</h3>
<p>To visualize the need to look at each group separately and each individually separately, we plotted the number of activities and levels of motivation for all individuals within each group. <a href="#fig-Analy" class="quarto-xref">Figure&nbsp;<span>4.2</span></a> shows the relationship between motivation and the number of activities by group before taking into account the FE.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-Analy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Analy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_results_files/figure-html/fig-Analy-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Analy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: Motivation vs.&nbsp;number of activities for all three groups.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This analysis revealed that, without accounting for FE, there is no significant relationship between the number of activities and motivation in the control group. However, for the autism group, a steep slope indicates that as the number of activities increases, so does motivation. The social anxiety group also shows a positive slope, though less pronounced, suggesting a correlation between increased activities and higher motivation levels. These findings contradict existing literature, which support that motivation in the autism and social anxiety groups should not necessarily rise with more activities, underscoring the importance of using the FE model.</p>
<p><a href="#fig-FEAnaly" class="quarto-xref">Figure&nbsp;<span>4.3</span></a> presents plots illustrating the influence of activities on motivation. The dashed pooling line represents the intercept and slope if all data were analyzed together, while the solid lines show individual lines of best fit for each participant. This means each individual has a different intercept, but all share the same slope.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-FEAnaly" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-FEAnaly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_results_files/figure-html/fig-FEAnaly-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FEAnaly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.3: FE model for motivation vs.&nbsp;number of activities for all participants.
</figcaption>
</figure>
</div>
</div>
</div>
<p>While modeling each participant individually is crucial for accounting for varying baseline levels of motivation, we found that applying a FE model to each group—control, autism, and social anxiety—was also important for understanding the true relationship between the number of activities and motivation, as each group may have different baseline levels.</p>
<p><a href="#fig-groupFE" class="quarto-xref">Figure&nbsp;<span>4.4</span></a> presents the results of the FE models for all three groups. These models predict motivation based on the number of activities while considering both individual and group baseline differences. This approach allows for a more accurate assessment of the impact of activities on motivation within each distinct group. The plots illustrate unique patterns for each group, emphasizing the value of tailored analyses. Notably, the autism and social anxiety groups show steeper slopes when all data are pooled together; however, when individuals are analyzed separately, the slopes for each group are much less steep. These results align more closely with expectations from existing literature.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-groupFE" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-groupFE-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_results_files/figure-html/fig-groupFE-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-groupFE-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.4: FE model for motivation vs.&nbsp;number of activities by group.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Since the FE models require both an evening survey response for motivation and the number of activities determined by the DBSCAN-TE algorithm, some data were lost. This reduced the sample size from 31 to 23 in the control group, from 29 to 17 in the autism group, and from 28 to 22 in the social anxiety group. The FE models need enough data points for each participant to ensure effective analysis, which explains the reduction in participants. After visualizing the relationships, we proceeded with running the FE models for each group. The results from these models are presented in <a href="#tbl-groupFEAnaly" class="quarto-xref">Table&nbsp;<span>4.6</span></a>.</p>
<div class="cell">
<div id="tbl-groupFEAnaly" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-groupFEAnaly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.6: FE Models: Motivation and Number of Activities by Group
</figcaption>
<div aria-describedby="tbl-groupFEAnaly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Control</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Autism</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Social Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No. of Activities</td>
<td style="text-align: center;">0.259+</td>
<td style="text-align: center;">0.361</td>
<td style="text-align: center;">0.483*</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(1.716)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(1.147)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(2.149)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No. of Obs.</td>
<td style="text-align: center;">1,167</td>
<td style="text-align: center;">451</td>
<td style="text-align: center;">1,033</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">9,177.454</td>
<td style="text-align: center;">3,597.049</td>
<td style="text-align: center;">8,797.231</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R²</td>
<td style="text-align: center;">0.003</td>
<td style="text-align: center;">0.003</td>
<td style="text-align: center;">0.004</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Robust t-statistics in parentheses. + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<p>The FE models for the control, autism, and social anxiety groups revealed different relationships between the number of activities and motivation. For the control group, the coefficient was 0.259, suggesting a marginally positive but not strongly significant relationship. In the autism group, the coefficient was 0.361, also indicating a positive but statistically insignificant relationship between activities and motivation. However, the social anxiety group had a coefficient of 0.483, showing a statistically significant positive relationship. This suggests that increasing activities is notably linked to higher motivation for individuals with social anxiety.</p>
<p>These findings underscore the importance of recognizing individual differences across groups. The significant positive relationship in the social anxiety group suggests that increasing activities could be particularly effective in enhancing motivation for this population. In contrast, the control and autism groups did not show strong evidence of this relationship, indicating that other factors might play a more critical role in influencing motivation for these groups.</p>
</section>
<section id="motivation-and-suicidal-ideation" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="motivation-and-suicidal-ideation"><span class="header-section-number">4.6.2</span> Motivation and Suicidal Ideation</h3>
<p>The prevalence of suicidal ideation across the groups underscores the complex interplay between mental health and activity engagement. The literature suggests that suicidal behavior is negatively associated with overall well-being <span class="citation" data-cites="fonseca-pedreroRiskProtectiveFactors2022 fumeroAdolescentsBipolarExperiences2021">(<a href="references.html#ref-fonseca-pedreroRiskProtectiveFactors2022" role="doc-biblioref">Fonseca-Pedrero et al., 2022</a>; <a href="references.html#ref-fumeroAdolescentsBipolarExperiences2021" role="doc-biblioref">Fumero et al., 2021</a>)</span>. Since we connected motivation to well-being, a similar association is drawn between suicidal tendency and motivation.</p>
<p>Based on similar conclusions from the motivation and number of activities analysis, we continued to perform the analysis by group. <a href="#tbl-groupFESuic" class="quarto-xref">Table&nbsp;<span>4.7</span></a> shows the FE models for the impact of suicidal intensity, which was scored from 1-100, on level of motivation, which was also scored from 1-100, for individuals by group.</p>
<div class="cell">
<div id="tbl-groupFESuic" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-groupFESuic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.7: FE Models: Motivation and Suicidal Intensity by Group
</figcaption>
<div aria-describedby="tbl-groupFESuic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Autism</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Social Anxiety</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Control</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Suicidal Intesity</td>
<td style="text-align: center;">−0.095+</td>
<td style="text-align: center;">−0.160***</td>
<td style="text-align: center;">−0.361**</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(−1.927)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(−5.518)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(−3.293)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No. of Obs.</td>
<td style="text-align: center;">484</td>
<td style="text-align: center;">822</td>
<td style="text-align: center;">66</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">3,942.104</td>
<td style="text-align: center;">6,934.607</td>
<td style="text-align: center;">568.685</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R²</td>
<td style="text-align: center;">0.012</td>
<td style="text-align: center;">0.04</td>
<td style="text-align: center;">0.113</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Robust t-statistics in parentheses. + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<p>The FE models for the autism, social anxiety, and control groups show distinct relationships between suicidal intensity and motivation levels. In the autism group, the coefficient for suicidal intensity is -0.095, indicating a marginally significant negative relationship, suggesting that higher suicidal intensity may slightly reduce motivation, though the evidence is weak. In contrast, the social anxiety group shows a coefficient of -0.160, with a statistically significant negative relationship, meaning higher suicidal intensity is strongly linked to decreased motivation. Similarly, the control group’s coefficient is -0.361, with a significant negative relationship, showing that increased suicidal intensity is associated with notably lower motivation levels.</p>
<p>These findings emphasize the need to consider the impact of suicidal intensity on motivation within each group. While the relationship is negative across all groups, the varying strength and significance highlight the necessity for tailored interventions to address motivational challenges in each population.</p>
</section>
</section>
<section id="activity-types" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="activity-types"><span class="header-section-number">4.7</span> Activity Types</h2>
<p>We examined how the number of activities at different locations—such as parks, grocery stores, libraries, and social recreation spaces—impacts motivation across each group. The analysis factored in activity counts determined by the DBSCAN-TE algorithm, along with seven-day and 14-day moving averages. While all activity locations and measurements were included, only a few yielded statistically significant results. Notably, significant findings emerged for the seven-day average park activities and daily grocery store activities, highlighting their potential influence on individual motivation levels.</p>
<section id="activities-at-parks" class="level3" data-number="4.7.1">
<h3 data-number="4.7.1" class="anchored" data-anchor-id="activities-at-parks"><span class="header-section-number">4.7.1</span> Activities at Parks</h3>
<p><a href="#tbl-groupFEParks" class="quarto-xref">Table&nbsp;<span>4.8</span></a> presents the FE models for the seven-day rolling average number of activities at parks for the three groups.</p>
<div class="cell">
<div id="tbl-groupFEParks" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-groupFEParks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.8: FE Models: Motivation and Number of Activities at Parks by Group
</figcaption>
<div aria-describedby="tbl-groupFEParks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Control</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Autism</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Social Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Seven-Day Park</td>
<td style="text-align: center;">3.017*</td>
<td style="text-align: center;">4.938</td>
<td style="text-align: center;">1.511</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(2.239)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.857)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.207)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No. of Obs.</td>
<td style="text-align: center;">1,840</td>
<td style="text-align: center;">774</td>
<td style="text-align: center;">1,597</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">14,509.34</td>
<td style="text-align: center;">6,215.856</td>
<td style="text-align: center;">13,615.11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R²</td>
<td style="text-align: center;">0.002</td>
<td style="text-align: center;">0.001</td>
<td style="text-align: center;">0</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Robust t-statistics in parentheses. + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<p>In examining park activities, statistically significant results were observed solely for the control group. A positive correlation emerged, indicating that each additional park activity within a seven-day period corresponded with a 3.017-point increase in motivation score. This suggests that frequent park visits over a week are linked to heightened motivation levels among individuals in the control group. Conversely, the analysis did not unveil any significant correlation between park visits and motivation levels for the autism and social anxiety groups. This implies that park activities within the examined time frames do not notably affect motivation levels for these groups.</p>
</section>
<section id="activities-at-grocery-stores" class="level3" data-number="4.7.2">
<h3 data-number="4.7.2" class="anchored" data-anchor-id="activities-at-grocery-stores"><span class="header-section-number">4.7.2</span> Activities at Grocery Stores</h3>
<p><a href="#tbl-groupFEGrocery" class="quarto-xref">Table&nbsp;<span>4.9</span></a> presents the FE models for the number of activities at grocery stores for the three groups.</p>
<div class="cell">
<div id="tbl-groupFEGrocery" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-groupFEGrocery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.9: FE Models: Motivation and Number of Activities at Grocery Stores by Group
</figcaption>
<div aria-describedby="tbl-groupFEGrocery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Control</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Autism</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Group: Social Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Grocery Store</td>
<td style="text-align: center;">−2.690+</td>
<td style="text-align: center;">−2.725***</td>
<td style="text-align: center;">0.519</td>
</tr>
<tr class="even">
<td style="text-align: left; box-shadow: 0px 1.5px;"></td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(−1.878)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(−3.721)</td>
<td style="text-align: center; box-shadow: 0px 1.5px;">(0.614)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No. of Obs.</td>
<td style="text-align: center;">1,167</td>
<td style="text-align: center;">451</td>
<td style="text-align: center;">1,033</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">9,178.666</td>
<td style="text-align: center;">3,598.227</td>
<td style="text-align: center;">8,801.453</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R²</td>
<td style="text-align: center;">0.002</td>
<td style="text-align: center;">0.001</td>
<td style="text-align: center;">0</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Robust t-statistics in parentheses. + p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<p>The examination of grocery store visits unveiled intriguing trends across the different groups. Notably, a statistically significant negative correlation was found for the autism group, indicating a decrease in motivation by 2.725 points with each additional grocery store activity (p &lt; 0.001). Similarly, the control group exhibited a slight negative correlation (p &lt; 0.1), with each additional daily extra grocery store visit reducing motivation by 2.690 points. Conversely, no statistical significance was observed for the social anxiety group. These findings underscore a nuanced connection between grocery store visits and motivation, with notable negative impacts identified in the autism group, while no significant associations were evident in the control and social anxiety groups.</p>
</section>
<section id="activity-impact-on-motivation" class="level3" data-number="4.7.3">
<h3 data-number="4.7.3" class="anchored" data-anchor-id="activity-impact-on-motivation"><span class="header-section-number">4.7.3</span> Activity Impact on Motivation</h3>
<p>These findings are important because they reveal how activities impact mental well-being differently for individuals with autism, social anxiety, and those without these conditions. For the control group, the positive correlation with seven-day average park visits suggests outdoor activities benefit overall well-being. Conversely, the negative correlation with grocery store visits for the autism group highlights the stress linked to routine tasks like grocery shopping. Understanding these differences is key to designing tailored interventions. For example, promoting park visits could boost well-being in the general population, while reducing stress in grocery environments could aid autistic individuals. The lack of significant results for specific locations in the social anxiety group suggests that overall activity levels, rather than specific locations, may be more crucial to their well-being.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-fonseca-pedreroRiskProtectiveFactors2022" class="csl-entry" role="listitem">
Fonseca-Pedrero, E., Al-Halabí, S., Pérez-Albéniz, A., &amp; Debbané, M. (2022). Risk and protective factors in adolescent suicidal behaviour: <span>A</span> network analysis. <em>International Journal of Environmental Research and Public Health</em>, <em>19</em>(3), 1784. <a href="https://doi.org/10.3390/ijerph19031784">https://doi.org/10.3390/ijerph19031784</a>
</div>
<div id="ref-fumeroAdolescentsBipolarExperiences2021" class="csl-entry" role="listitem">
Fumero, A., Marrero, R. J., Pérez-Albéniz, A., &amp; Fonseca-Pedrero, E. (2021). Adolescents’ bipolar experiences and suicide risk: <span class="nocase">Well-being</span> and mental health difficulties as mediators. <em>International Journal of Environmental Research and Public Health</em>, <em>18</em>(6), 3024. <a href="https://doi.org/10.3390/ijerph18063024">https://doi.org/10.3390/ijerph18063024</a>
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_methods.html" class="pagination-link" aria-label="Methodology">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Methodology</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05_conclusions.html" class="pagination-link" aria-label="Conclusions">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Conclusions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>