# Discussion and Applications {#sec-contribs}

We explored the percent of days that each group was suicidal. This percent calculation is based on the total number of days for each group and the number of days within each group a participant answered “Yes” to the question: “Have you thought about killing yourself in the past 12 hours or since you last took a survey?” that was asked as part of the evening survey.

@tbl-groupsuicide table shows these percentages.

```{r table neuro suicide, echo=FALSE, message = FALSE}
#| label: tbl-groupsuicide
#| tbl-cap: "Percent Suicidal Ideation"

library(targets)
tar_load(tbl_neuro_suicide)
tbl_neuro_suicide
```

This table presents the percentage of days individuals within different groups reported feeling suicidal. Notably, individuals in the control group reported feeling suicidal on approximately 1.04% of the days. In contrast, individuals diagnosed with autism reported a substantially higher percentage, with 13.38% of days marked by suicidal feelings. Similarly, those with social anxiety exhibited the highest percentage, with 24.79% of days characterized by feelings of suicidality. These findings suggest a significant disparity in the prevalence of suicidal ideation across groups, with higher rates observed among individuals with autism and social anxiety compared to the control group. Understanding these patterns is crucial for developing targeted interventions and support strategies tailored to individuals with specific neurodiverse conditions.
