project:
  type: book

# This defines the .qmd files that are in your document
book:
  title: "Classifying GPS Points to Daily Activities using Simultaneously Optimized DBSCAN-TE Parameters."
  author:
    - name: Gregory S. Macfarlane
      orcid: 0000-0003-3999-7584
      email: gregmacfarlane@byu.edu
      affiliations:
        - id: byuce
          name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          country: USA
          postal-code: 84602
    - name: Gillian Martin
      email: gregmacfarlane@gmail.com
      affiliations:
        - ref: byuce
    - name: Emily Blanchard
      email: emmykae@byu.edu
      affiliations:
        - ref: byuce
    - name: Jared Nielsen
      orcid: 0000-0002-2717-193X
      email: jarednielsen@byu.edu
      affiliations:
      - id: byupsych
        name: Psychology Department, Brigham Young University
        address: 1070 KMBL
        city: Provo
        state: UT
        country: USA
        postal-code: 84602
  date: "9/30/2023"
  chapters:
    - index.qmd
    - 03_methods.qmd
    - 04_results.qmd
    - 05_conclusion.qmd
    - acknowledgments.qmd
    - references.qmd
  keyword: "active mobility, life-stages, and quality of life"
  abstract: |
    Location-based services data collected from mobile phones represents a potentially
    powerful source of travel behavior data, but transforming the raw location data
    into semantic activities --- where and when activities occurred --- is non-trivial.
    In particular, existing algorithms to label activities require multiple parameters
    that require calibration to a particular dataset. In this research, we apply a 
    simulated annealing optimization procedure to identify the values of four parameters
    used in a density-based spatial clustering with additional noise and time entropy
    (DBSCAN-TE) algorithm. We develop a spatial accuracy scoring function to use 
    in the calibration methodology, and apply the calibrated parameters to a complete
    dataset of individuals participating in a psychological study, revealing a significant
    relationship between the number of daily activities and neurotypology.



bibliography: [byu-capsanxiety.bib, packages.bib]
csl: ieee-with-url.csl

format:
  html:
    theme: cosmo
  ieee-conference-pdf:
    include-in-header: 
      - packages.tex
    natbib: false
    keep-tex: true
    top-level-division: section

editor: visual

