project:
  type: book

execute:
  cache: true
  freeze: auto
  echo: false
  warning: false

# layout: fancy, oneside, masters
layout: masters
department: Civil and Construction Engineering
student: Emily Kae Youngs
chair: Gregory S. Macfarlane
committee:
  - Jared A. Nielsen
  - Grant G. Schultz

# Title with custom formatting for fancy title page
customtitle: |
    | Exploring the Link Between
    | Travel Behavior and Mental Health
book:
  output-file: "Exploring the link between travel behavior and mental health"
  title: |
    | Exploring the Link Between
    | Travel Behavior and Mental Health
  author:
    - name: Emily K. Youngs
      orcid: 0009-0001-6847-1154
      email: emmykae@byu.edu
      affiliations:
        - id: byuce
          name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          country: USA
          postal-code: 84602
    - name: Gregory S. Macfarlane
      orcid: 0000-0003-3999-7584
      email: gregmacfarlane@byu.edu
      affiliations:
        - ref: byuce
    - name: Jared A. Nielsen
      orcid: 0000-0002-2717-193X
      email: jarednielsen@byu.edu
      affiliations:
      - id: byupsych
        name: Psychology Department, Brigham Young University
        address: 1070 KMBL
        city: Provo
        state: UT
        country: USA
        postal-code: 84602
    - name: Grant G. Schultz
      orcid: 0000-0002-0675-2970
      email: gschultz@byu.edu
      affiliations:
        - ref: byuce
  date: "5/28/2024"
  chapters:
    - index.qmd
    - 02_litreview.qmd
    - 03_methods.qmd
    - 04_results.qmd
    - 05_conclusions.qmd
    - 06_limitations.qmd
    # - acknowledgments.qmd
    - references.qmd
  abstract: |
    This study explores the critical link between travel behavior and mental 
    health, focusing on young adults who have expressed suicidal ideation. By 
    analyzing how daily activities and movement patterns impact mental well-being, 
    the research aims to explore travel related mental health approaches for 
    individuals. The importance of this work lies in 
    its potential to improve the quality of life for individuals by 
    informing more personalized and effective mental health strategies.

    Through comprehensive data analysis and statistical modeling, the research aims to uncover 
    insights into how travel behavior influences motivation levels and mental 
    well-being across different neurological and physiological groups. The dataset used in this 
    study includes location-based services (LBS) data collected from participants 
    over varying periods of time, allowing for a longitudinal analysis of travel patterns 
    and mental health parameters for individuals.
    
    Participants were part of either autism, social anxiety, or control groups, 
    and their travel behavior and mental health data were analyzed using statistical
    models. The relationship between suicidality, motivation levels, and travel 
    behaviors was explored, along with the impact of engagement in activities at
    different location types on motivation levels. The study used the DBSCAN-TE 
    (density-based spatial clustering of applications with noise, time, and entropy)
    algorithm to identify activities from the LBS data, with efforts made to 
    address data quality issues and impute missing activity information.
    
    Significant differences in activity engagement and motivation levels were 
    observed among individuals in the autism, social anxiety, and control groups. 
    The study found that those in the control group took part in more activities 
    and expressed higher levels of motivation than those in the autism or social 
    anxiety groups. In addition, simply increasing activity engagement may not 
    be sufficient to significantly boost motivation levels. However, for those in 
    the control group, more activities in parks lead to a statistically significant
    increase in motivation and for those in the autism group, more activities to
    grocery stores lead to a statistically significant decrease in motivation. 
    The research highlights the complex interplay between travel behavior, 
    activity engagement, and mental health outcomes, emphasizing the need for 
    tailored interventions based on individual needs.
    
    The study faced limitations related to data quality, including sparse data
    due to participants turning off their phones or the app failing to record 
    data accurately. The lack of detailed information on activity duration and 
    the inability to confirm activity engagement for all participants were also 
    noted as limitations.
    
    All in all, this research sheds light on the complex relationship 
    between travel behavior and mental health among young adults with suicidal 
    ideation. By understanding how travel patterns impact motivation levels and
    mental well-being, tailored interventions can be developed to support 
    individuals grappling with mental health challenges. Future studies should 
    focus on improving data quality and incorporating measures to enhance the 
    reliability of activity data collection for more robust analyses.

keywords:
  - travel behavior
  - mental health
  - motivation
  - suicidality
  - activity types
  - DBSCAN-TE
 
acknowledgments: |
  I would like to express my gratitude to Dr. Macfarlane, my committee chair, as 
  well as to Dr. Schultz and Dr. Nielsen, for their invaluable guidance and support 
  in teaching me how to conduct research and write effectively. Their expertise 
  and encouragement have been instrumental in the completion of this thesis.
  I am also grateful to the BYU Civil and Construction Engineering Department 
  for providing the opportunities and resources necessary for my academic and 
  professional growth during my time at BYU.
  
  I would also like to express heartfelt thanks to my family and friends for 
  their unwavering support throughout this journey. 
  A special thank you to my husband, Josh, whose constant reassurance and encouragement
  have buoyed me up.
  
  The data used in this research was collected with help from an Interdisciplinary 
  Research Grant at Brigham Young University, and administered under IRB protocol 
  F2020-242. The investigators on the overarching grant include Terisa Gabrielsen, 
  Jared Nielsen, and Mikle South.

bibliography: groupreferences.bib
csl: apa.csl

format:
  html:
    theme: cosmo
  byu-thesis-pdf:
    keep-tex: true
    highlight-style: arrow
    include-in-header: 
      - packages.tex
    fig-pos: "H"
    
toc-depth: 3.0
    
editor: visual

