project:
  type: book

# This defines the .qmd files that are in your document
book:
  title: "Classifying location points as daily activities using simultaneously optimized DBSCAN-TE parameters."
  author:
    - name: Gregory S. Macfarlane
      orcid: 0000-0003-3999-7584
      email: gregmacfarlane@byu.edu
      affiliations:
        - id: byuce
          name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          country: USA
          postal-code: 84602
    - name: Gillian Riches
      affiliations:
        - ref: byuce
    - name: Emily K. Youngs
      affiliations:
        - ref: byuce
    - name: Jared A. Nielsen
      orcid: 0000-0002-2717-193X
      affiliations:
      - id: byupsych
        name: Psychology Department, Brigham Young University
        address: 1070 KMBL
        city: Provo
        state: UT
        country: USA
        postal-code: 84602
  date: "3/21/2024"
  chapters:
    - index.qmd
    - 03_methods.qmd
    - 04_results.qmd
    #- 05_conclusion.qmd
    - acknowledgments.qmd
    - references.qmd
  abstract: |
    Location-based services data collected from mobile phones represent a potentially
    powerful source of travel behavior data, but transforming the location points
    into semantic activities --- where and when activities occurred --- is non-trivial.
    Existing algorithms to label activities require multiple parameters
    calibrated to a particular dataset. In this research, we apply a 
    simulated annealing optimization procedure to identify the values of four parameters
    used in a density-based spatial clustering with additional noise and time entropy
    (DBSCAN-TE) algorithm. We develop a spatial accuracy scoring function to use 
    in the calibration methodology and identify paths for future research.


keywords:
  - Activity locations
bibliography: [byu-capsanxiety.bib, packages.bib]
cite-method: citeproc
csl: apa.csl

format:
  html:
    theme: cosmo
  elsevier-pdf:
    include-in-header: 
      - packages.tex
    journal:
      name: Findings
      formatting: review
      model: 3p
    keep-tex: true
    top-level-division: section
    toc: false

