project:
  type: book

execute:
  cache: true
  freeze: auto
  echo: false
  warning: false

department: Civil and Construction Engineering
student: Emily Kae Youngs
chair: Gregory S. Macfarlane
committee:
  - Jared A. Nielsen
  - Grant G. Schultz

# Title with custom formatting for fancy title page
book:
  output-file: "caps-anxiety"
  title:  Exploring the Link Between Travel Behavior and Mental Health
  author:
    - name: Emily K. Youngs
      orcid: 0009-0001-6847-1154
      email: emmykae@byu.edu
      affiliations:
        - id: byuce
          name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          country: USA
          postal-code: 84602
    - name: Gregory S. Macfarlane
      orcid: 0000-0003-3999-7584
      email: gregmacfarlane@byu.edu
      affiliations:
        - ref: byuce
    - name: Jared A. Nielsen
      orcid: 0000-0002-2717-193X
      email: jarednielsen@byu.edu
      affiliations:
      - id: byupsych
        name: Psychology Department, Brigham Young University
        address: 1070 KMBL
        city: Provo
        state: UT
        country: USA
        postal-code: 84602
  date: "10/10/2024"
  chapters:
    - index.qmd
    - 02_litreview.qmd
    - 03_methods.qmd
    - 04_results.qmd
    - 05_conclusions.qmd
    - 06_limitations.qmd
    - acknowledgments.qmd
    - references.qmd
  abstract: |
    The mental health of young adults is an important social consideration,
    given increasing rates of isolation, depression, anxiety, suicide, and other 
    ills. But the effect of daily travel on mental health 
    --- or the effect of mental health on daily travel --- is not well understood.
    In this research, we explore the relationship between mental health and 
    observed trip-making behavior in a longitudinal dataset of young adults. 
    The participants in this study all expressed suicidal ideation in
    professional treatment setting and have an accompanying psychiatric diagnosis for social
    anxiety disorder, autism spectrum disorder, or are in a designated control group.
    Participants volunteered to use a mobile device application that surveyed them twice
    a day for several months on their reported mood while also tracking their
    physical location via location-based services. 
    We find significant differences in activity engagement and motivation 
    levels among the groups: The control group participated in more activities and 
    reported higher motivation compared to the autism and social anxiety groups. 
    Increased activity engagement did not consistently raise motivation levels; however,
    for those in the control group, more activities in parks lead to a 
    statistically significant increase in motivation and for those in the autism 
    group, more activities to grocery stores lead to a statistically significant 
    decrease in motivation. 


keywords:
  - travel behavior
  - mental health
  - motivation
  - suicidality
  - activity types
  - DBSCAN-TE
 
acknowledgments: |
  I would like to express my gratitude to Dr. Macfarlane, my committee chair, as 
  well as to Dr. Schultz and Dr. Nielsen, for their invaluable guidance and support 
  in teaching me how to conduct research and write effectively. Their expertise 
  and encouragement have been instrumental in the completion of this thesis.
  I am also grateful to the BYU Civil and Construction Engineering Department 
  for providing the opportunities and resources necessary for my academic and 
  professional growth during my time at BYU.
  
  I would also like to express heartfelt thanks to my family and friends for 
  their unwavering support throughout this journey. 
  A special thank you to my husband, Josh, whose constant reassurance and encouragement
  have buoyed me up.
  
  The data used in this research was collected with help from an Interdisciplinary 
  Research Grant at Brigham Young University, and administered under IRB protocol 
  F2020-242. The investigators on the overarching grant include Terisa Gabrielsen, 
  Jared Nielsen, and Mikle South.

bibliography: groupreferences.bib
cite-method: citeproc
csl: apa.csl

format:
  html:
    theme: cosmo
  elsevier-pdf:
    journal: 
      name: Travel Behaviour and Society
      formatting: review
      model: 3p
    keep-tex: true
    highlight-style: arrow
    top-level-division: section
    include-in-header: 
      - packages.tex
    fig-pos: "H"
    toc: false

    
toc-depth: 3.0
    

editor:
  markdown:
    wrap: sentence