project:
  type: book

# This defines the .qmd files that are in your document
book:
  title: "Exploring the link between travel behavior and mental health."
  author:
    - name: Gregory S. Macfarlane
      orcid: 0000-0003-3999-7584
      email: gregmacfarlane@byu.edu
      affiliations:
        - id: byuce
          name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          country: USA
          postal-code: 84602
    - name: Emily K. Youngs
      orcid: 0009-0001-6847-1154
      email: emmykae@byu.edu
      affiliations:
        - ref: byuce
    - name: Gillian Martin
      email: gregmacfarlane@gmail.com
      affiliations:
        - ref: byuce
    - name: Jared A. Nielsen
      orcid: 0000-0002-2717-193X
      email: jarednielsen@byu.edu
      affiliations:
      - id: byupsych
        name: Psychology Department, Brigham Young University
        address: 1070 KMBL
        city: Provo
        state: UT
        country: USA
        postal-code: 84602
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - 02_litreview.qmd
    - 03_methods.qmd
    - 04_results.qmd
    - 06_limitations.qmd
    - 07_conclusions.qmd
    - acknowledgments.qmd
    - references.qmd
  keyword: "active mobility, life-stages, and quality of life"
  abstract: |
    NEED TO WRITE
    The mental health of young adults is a major concern in much of the world. The causes of this concern are not straightforward, and multiple factors have been considered.
    Travel behavior is proposed as an element in individual mental health in a number of dimensions. 
    In this research, we explore a unique dataset of young adults who have expressed suicide ideation in professional therapy contexts. Using data from a mobile application revealing the individual's overall well-being and travel behaviors over a six-month period, we examine the relationship between travel behavior and expressed suicidal ideation.

bibliography: groupreferences.bib

format:
  html:
    theme: cosmo
  elsevier-pdf:
    include-in-header: 
      - packages.tex
    journal:
      name: 17th International Conference on Travel Behaviour Research
      cite-style: authoryear
    keep-tex: true
    top-level-division: section
    toc: false

editor: visual

